
language:

install: ./install-dependencies.sh

before_script:
  - "export PATH=$PATH:$HOME/build/bats/bin"

script: make install && CS=dark PREFIX=/usr/local make -f Makefile.mkdoc

branches:
  only:
  - master
  - devel
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
  global:
    - Build_Deps_Default_Paths=1
  matrix:
    - ENV= CS=dark PREFIX=.
    - ENV= CS=dark PREFIX=~/bin
    #- ENV=production CS=dark PREFIX=/usr/local

