
language: perl

perl:
  - "5.8"

install:
  - PREFIX=$DEP_PREFIX ./install-dependencies.sh
  - cpanm -h
  - cpanm --install URI::Escape

before_script: []

script: ./configure && ./install.sh && make stat build test -f Makefile.mkdoc

branches:
  only:
  - master
  - devel
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
  global:
    - Build_Deps_Default_Paths=1
    - PATH=$PATH:$PREFIX/bin
    - DEP_PREFIX=$HOME/.local
  matrix:
    - ENV= CS=dark PREFIX=.
    #- ENV= CS=dark PREFIX=$HOME/.local
    #- ENV=production CS=dark PREFIX=/usr/local

