
language: perl

perl:
  - "5.8"

addons:
  apt:
    packages:
      - tree
      - realpath
      - uuid-runtime
      - moreutils
      - tidy

install:
  - PREFIX=$DEP_PREFIX ./install-dependencies.sh all
  - pip install --user -r requirements.txt
  - cpanm -h
  - cpanm --install URI::Escape

before_script: []

script:
  - ./configure
  - test "$PREFIX" = "./usr" || ./install.sh 
  - make stat build test -f Makefile.mkdoc

branches:
  only:
  - master
  - devel
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
  global:
    - DEP_PREFIX=$HOME/.local
    - PATH=$PATH:$DEP_PREFIX/bin:$PREFIX/bin
    - Build_Deps_Default_Paths=1
  matrix:
    - ENV=development CS=dark PREFIX=./usr
    #- ENV=testing CS=dark PREFIX=$HOME/.local
    #- ENV=production CS=dark PREFIX=/usr/local

